name: llava_pathvqa_openended
model_id: chaoyinshe/llava-med-v1.5-mistral-7b-hf
dataset: flaviagiammarino/path-vqa
question_set: open-ended
hallscore_csv: outputs/llava_pathvqa_openended_hallscore.csv
green_csv: outputs/llava_pathvqa_openended_green.csv
